version: "3.3"
services:
  mongodb_container:
    container_name: fast_mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      # - ./db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  nginx:
    container_name: nginx_compiler
    restart: always
    build: ./nginx
    depends_on:
      - web
    ports:
      - "6688:80"
      - "6699:443"
  web:
    container_name: flask_compiler
    tty: true
    build: .
    expose:
      - 5000
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      FLASK_ENV: production
    depends_on:
      - mongodb_container

