env:
  REGISTRY: "registry.digitalocean.com/unownone"
  IMAGE_NAME: "fastcompiler"

name: Test, Build and publish

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create ENV
        run: |
            touch .env
            echo MONGO_ROOT_USERNAME=dummy_username
            echo MONGO_ROOT_PASS=dummy_password
            echo MONGO_DB_NAME=dummy
            MongoUserName=dumdum
            MongoPassWord=Dum123b
            cat .env
      - name: Build
        run: docker-compose up -d
      - name: Test
        run: pytest --cov=app tests/ 
  
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: SSH to droplet |
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,COMMAND
          script: |
            #Move into directory
            cd Fast-online-compiler
            # fetch latest update
            git pull 
            # Stop running container
            docker-compose up -d --build
