env:
  REGISTRY: "registry.digitalocean.com/unownone"
  IMAGE_NAME: "fastcompiler"

name: Build and publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_and_push

    steps:
      - name: SSH to droplet |
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,COMMAND
          script: |
            #Move into directory
            cd Fast-online-compiler
            # Pull latest update
            git pull
            # Stop running container
            docker-compose up -d --build
