name: Testing

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: [ master, main ]

jobs:        
  pytest:
    runs-on: ubuntu-latest
    environment: CI Environment
    steps:
      - uses: actions/checkout@v2 
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Run Tests
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export PATH=${PATH}:/usr/lib/jvm/java-6-open-jdk/bin
          apt-get install gcc openjdk-11-jdk g++ python3 python3-pip nodejs -y --fix-missing
          pip install -r requirements.txt
          pytest tests/ --cov=app tests/ --junit-xml=test-reports/report.xml --cov-report=term-missing --cov-fail-under=90 | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        if: ${{ always() && github.ref != 'refs/heads/master' }}
        with:
          create-new-comment: true
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./test-reports/report.xml
      - name: Evaluate Coverage
        if: env.STATUS == 'FAIL'
        run: exit 1